name: CI Test

on: [push, pull_request]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  VERSION: ${{ github.event.pull_request.number }}

permissions:
  contents: read
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Template react-zustand Code Check
        run: |
          cd templates/template-react-zustand
          pnpm install
          pnpm lint --no-cache
          pnpm tsc
      
      - name: Template react-ts Code Check
        run: |
          cd templates/template-react-ts
          pnpm install
          pnpm lint --no-cache
          pnpm tsc